SELECT 'PHOTO_FILE_NAME,PHOTO_TIMESTAMP_UTC,PHOTO_TIMESTAMP_AK_Local,LATITUDE_WGS84,LONGITUDE_WGS84,ALTITUDE,SURVEY_TYPE,COUNT_ADULT,COUNT_PUP,KELP_PRESENT,LAND_PRESENT,IMAGE_QUALITY
      ,COUNTED_BY,COUNTED_DATE,PROTOCOL,QUALITY_FLAG,ORIGINAL_FILENAME,FLOWN_BY,CAMERA_SYSTEM,VALIDATED_BY'
UNION ALL
SELECT
[PHOTO_FILE_NAME] + ',' +
[PHOTO_TIMESTAMP_UTC] + ',' +
[PHOTO_TIMESTAMP_AK_Local] + ',' +
CAST([LATITUDE_WGS84] AS nvarchar) + ',' +
CAST([LONGITUDE_WGS84] AS nvarchar) + ',' +
CAST([ALTITUDE] AS nvarchar) + ',' +
[SURVEY_TYPE] + ',' +
CAST([COUNT_ADULT] AS nvarchar) + ',' +
CAST([COUNT_PUP] AS nvarchar) + ',' +
CASE WHEN [KELP_PRESENT] IS NULL THEN '' ELSE [KELP_PRESENT] END + ',' +
CASE WHEN [LAND_PRESENT] IS NULL THEN '' ELSE [LAND_PRESENT] END + ',' +
CASE WHEN [IMAGE_QUALITY] IS NULL THEN '' ELSE [IMAGE_QUALITY] END + ',' +
[COUNTED_BY] + ',' +
[COUNTED_DATE] + ',' +
[protocol] + ',' +
CASE WHEN [QUALITY_FLAG] IS NULL THEN '' ELSE [QUALITY_FLAG] END + ',' +
CASE WHEN [ORIGINAL_FILENAME] IS NULL THEN '' ELSE [ORIGINAL_FILENAME] END + ',' +
CASE WHEN [FLOWN_BY] IS NULL THEN '' ELSE [FLOWN_BY] END + ',' +
CASE WHEN [CAMERA_SYSTEM] IS NULL THEN '' ELSE [CAMERA_SYSTEM] END + ',' +
[VALIDATED_BY]
 FROM [SO].[view_SO_D_allrecs_w_lookups]
  where SURVEY_TYPE = 'Optimal'
  and datepart(year,photo_timestamp_utc) = 2022
